/**
 * Continuous Image Carousel With Lightbox — Gutenberg block (editor side).
 * Dynamic block: the frontend markup is always generated by the same PHP
 * function as the [print_continuous_slider_plus_lightbox] shortcode, so the
 * block, the shortcode, and the admin "Preview Slider" page can never drift
 * apart — including which Slider/Lightbox Engine is active.
 *
 * No build step on purpose (this plugin has no npm/webpack setup) — plain
 * wp.element.createElement calls instead of JSX.
 */
( function ( blocks, element, blockEditor, components, ServerSideRender, i18n, data ) {
    'use strict';

    var el = element.createElement;
    var Fragment = element.Fragment;
    var __ = i18n.__;
    var InspectorControls = blockEditor.InspectorControls;
    var PanelBody = components.PanelBody;
    var ExternalLink = components.ExternalLink;
    var Notice = components.Notice;
    var useSelect = data && data.useSelect;

    blocks.registerBlockType( 'cicwl/continuous-carousel', {
        title: __( 'Continuous Image Carousel', 'continuous-image-carousel-with-lightbox' ),
        description: __( 'Your continuous scrolling image carousel with lightbox.', 'continuous-image-carousel-with-lightbox' ),
        icon: 'images-alt2',
        category: 'media',
        keywords: [ 'carousel', 'slider', 'gallery', 'lightbox', 'continuous' ],
        supports: {
            html: false,
            align: [ 'wide', 'full' ]
        },

        edit: function ( props ) {
            var settingsUrl = ( window.cicwlBlockData && window.cicwlBlockData.settingsUrl ) || '';
            var proUrl = ( window.cicwlBlockData && window.cicwlBlockData.proUrl ) || '';

            // Free has exactly one slider, shared by every instance of this
            // block — so using it more than once in the same post means
            // every one of those instances shows identical content, which
            // is very likely not what someone intended. Surface that at the
            // moment it happens rather than leaving them to notice on the
            // published page.
            var instanceCount = useSelect
                ? useSelect( function ( select ) {
                      var editor = select( 'core/block-editor' );
                      return editor && editor.getGlobalBlockCount ? editor.getGlobalBlockCount( 'cicwl/continuous-carousel' ) : 1;
                  }, [] )
                : 1;
            var multipleInstances = instanceCount > 1;

            var multiInstanceNotice = ( multipleInstances && Notice )
                ? el(
                      Notice,
                      { status: 'warning', isDismissible: false },
                      el(
                          'span',
                          {},
                          __( 'This block is used more than once on this page — on Free, every instance shares the same slider (same images, same settings). ', 'continuous-image-carousel-with-lightbox' ),
                          proUrl
                              ? el( ExternalLink, { href: proUrl }, __( 'Pro gives each one its own independent slider.', 'continuous-image-carousel-with-lightbox' ) )
                              : null
                      )
                  )
                : null;

            return el(
                Fragment,
                {},
                el(
                    InspectorControls,
                    {},
                    el(
                        PanelBody,
                        { title: __( 'Carousel Settings', 'continuous-image-carousel-with-lightbox' ) },
                        multiInstanceNotice,
                        el(
                            'p',
                            {},
                            __(
                                'Images, speed, engine and lightbox options are managed on the plugin\u2019s settings page.',
                                'continuous-image-carousel-with-lightbox'
                            )
                        ),
                        settingsUrl
                            ? el(
                                  ExternalLink,
                                  { href: settingsUrl },
                                  __( 'Manage Images & Settings', 'continuous-image-carousel-with-lightbox' )
                              )
                            : null
                    )
                ),
                el(
                    'div',
                    { className: 'cicwl-block-editor-preview' },
                    multiInstanceNotice,
                    el(
                        'p',
                        { className: 'cicwl-block-editor-note' },
                        __(
                            'Live preview \u2014 the scrolling animation and lightbox only run on the published page.',
                            'continuous-image-carousel-with-lightbox'
                        )
                    ),
                    el( ServerSideRender, {
                        block: 'cicwl/continuous-carousel',
                        attributes: props.attributes
                    } )
                )
            );
        },

        // Dynamic block — PHP's render_callback produces the frontend markup.
        save: function () {
            return null;
        }
    } );
} )(
    window.wp.blocks,
    window.wp.element,
    window.wp.blockEditor,
    window.wp.components,
    window.wp.serverSideRender,
    window.wp.i18n,
    window.wp.data
);
